repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: check-merge-conflict
    - id: check-added-large-files
    # - id: name-tests-test
    #   args: ['--django']
    - id: detect-private-key
    - id: requirements-txt-fixer
    - id: check-yaml
    - id: check-json

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
    - id: flake8
      exclude: ^docs/|^install/

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
        exclude: ^rasa/__init__.py|^install/

-   repo: https://github.com/asottile/pyupgrade
    rev: v1.11.1
    hooks:
    -   id: pyupgrade

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.660
#     hooks:
#     -   id: mypy
#         language_version: python3
